# Generated by Django 5.1.6 on 2025-02-11 14:23

import functools
import import_export_extensions.models.export_job
import import_export_extensions.models.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_extensions', '0008_alter_exportjob_id_alter_importjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='data_file',
            field=models.FileField(help_text='File that contain exported data', max_length=512, storage=import_export_extensions.models.export_job.select_storage, upload_to=functools.partial(import_export_extensions.models.tools.upload_file_to, *(), **{'main_folder_name': 'export'}), verbose_name='Data file'),
        ),
    ]
