# Generated by Django 5.1.6 on 2025-02-12 11:15

import functools

from django.db import migrations, models

import import_export_extensions.models.export_job
import import_export_extensions.models.import_job
import import_export_extensions.models.tools


class Migration(migrations.Migration):
    dependencies = [
        (
            "import_export_extensions",
            "0008_alter_exportjob_id_alter_importjob_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="data_file",
            field=models.FileField(
                help_text="File that contain exported data",
                max_length=512,
                storage=import_export_extensions.models.export_job.export_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="export",
                ),
                verbose_name="Data file",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="data_file",
            field=models.FileField(
                help_text="File that contains data to be imported",
                max_length=512,
                storage=import_export_extensions.models.import_job.import_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="import",
                ),
                verbose_name="Data file",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="import_task_id",
            field=models.CharField(
                default=str,
                help_text="Celery task ID that starts with `import_data`",
                max_length=36,
                verbose_name="Import task ID",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="input_errors_file",
            field=models.FileField(
                help_text="File that contains failed rows",
                max_length=512,
                null=True,
                storage=import_export_extensions.models.import_job.import_error_storage,
                upload_to=functools.partial(
                    import_export_extensions.models.tools.upload_file_to,
                    *(),
                    main_folder_name="import",
                ),
                verbose_name="Input errors file",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="parse_task_id",
            field=models.CharField(
                default=str,
                help_text="Celery task ID that starts with `parse_data`",
                max_length=36,
                verbose_name="Parsing task ID",
            ),
        ),
    ]
