services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME}-user || false"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}-dev
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}-user
      - POSTGRES_PASSWORD=testpass
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: django-import-export-extensions/server:latest
    container_name: diee_django_server
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    entrypoint: ["wait-for", "-t", "120", "postgres:5432", "--", "/home/app/server/start-server.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  celery-worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    image: django-import-export-extensions/celery-worker:latest
    container_name: diee_celery_worker
    env_file: .env
    volumes:
      - ./media:/home/app/media
    depends_on:
      - postgres
    entrypoint: ["/home/celery/start-celery-worker.sh"]
